# Configuration for custom metadata (title and description) for .md files
metadata:
  # Global settings
  enabled: true
  
  # File-specific metadata configuration
  files:
    # Example configurations for different files
    # Path is relative to docs directory
    "index.md":
      title: "Sensitive data discovery tool with friendly UI for Mac, Win, Linux"
      description: "Advanced sensitive data discovery tool combining personal data discovery, payment card discovery, and passwords finder in one solution. Comprehensive data detector for compliance and security."
      # Language-specific overrides (optional)
      # If not specified, the default title/description will be auto-translated
      translations:
        ru:
          title: "Инструмент обнаружения конфиденциальных данных для Mac, Win, Linux"
        
    
    "angrydata-core/index.md":
      title: "Core Library | Angry Data Scanner"
      description: "Library for sensitive data processing"
    
    "CONSOLE.md":
      title: "Console Mode | Angry Data Scanner"
      description: "Using Angry Data Scanner in console mode"
  
  # Default metadata for files not explicitly configured
  defaults:
    description: "Advanced sensitive data discovery tool combining personal data discovery, payment card discovery, and passwords finder in one solution. Comprehensive data detector for compliance and security."
